export default function ReportPanel({ data }) {
  if (!data) {
    return (
      <div className="p-6 text-center text-gray-500 text-sm">
        Run analysis first to generate a report
      </div>
    );
  }

  const { site_info, layout, solar_data, shadow_analysis, yield_info } = data;

  return (
    <div className="p-4 space-y-4 text-sm">
      <h2 className="text-lg font-bold text-white">Site Assessment Report</h2>

      <section>
        <h3 className="text-amber-400 font-semibold mb-2">Site Information</h3>
        <table className="w-full">
          <tbody className="text-gray-300">
            <Row label="Location" value={`${site_info.latitude}N, ${site_info.longitude}W`} />
            <Row label="Altitude" value={`${site_info.altitude_m} m`} />
            <Row label="Zone Area" value={`${Math.round(site_info.polygon_area_m2).toLocaleString()} m²`} />
            <Row label="Terrain" value={site_info.terrain_classification} />
          </tbody>
        </table>
      </section>

      <section>
        <h3 className="text-amber-400 font-semibold mb-2">Layout</h3>
        <table className="w-full">
          <tbody className="text-gray-300">
            <Row label="Panels" value={layout.n_panels.toLocaleString()} />
            <Row label="Rows" value={layout.n_rows} />
            <Row label="Row Spacing" value={`${layout.row_spacing_m} m`} />
            <Row label="Module Area" value={`${Math.round(layout.total_module_area_m2).toLocaleString()} m²`} />
            <Row label="GCR" value={`${(layout.ground_coverage_ratio * 100).toFixed(1)}%`} />
          </tbody>
        </table>
      </section>

      <section>
        <h3 className="text-amber-400 font-semibold mb-2">Solar Resource</h3>
        <table className="w-full">
          <tbody className="text-gray-300">
            <Row label="Annual GHI" value={`${solar_data.annual_ghi_kwh_m2} kWh/m²`} />
            <Row label="Annual DNI" value={`${solar_data.annual_dni_kwh_m2} kWh/m²`} />
            <Row label="Avg Temp" value={`${solar_data.avg_temp_c} C`} />
            <Row label="Avg Wind" value={`${solar_data.avg_wind_speed_ms} m/s`} />
          </tbody>
        </table>
      </section>

      <section>
        <h3 className="text-amber-400 font-semibold mb-2">Energy Yield</h3>
        <table className="w-full">
          <tbody className="text-gray-300">
            <Row label="Capacity" value={`${yield_info.installed_capacity_mwc} MWc`} />
            <Row label="Annual Yield" value={`${yield_info.annual_yield_kwh.toLocaleString()} kWh`} />
            <Row label="Specific Yield" value={`${yield_info.specific_yield_kwh_kwp} kWh/kWp`} />
            <Row label="PR" value={`${(yield_info.performance_ratio * 100).toFixed(1)}%`} />
            <Row label="Shadow Loss" value={`${shadow_analysis.annual_shadow_loss_pct}%`} />
            <Row label="LCOE" value={`${yield_info.lcoe_eur_mwh} EUR/MWh`} />
            <Row label="CO2 Avoided" value={`${yield_info.co2_avoided_tons_yr} t/yr`} />
          </tbody>
        </table>
      </section>

      <div className="text-xs text-gray-600 pt-2 border-t border-gray-800">
        Generated by SolarSite | PVGIS-SARAH3 data | pvlib solar modeling
      </div>
    </div>
  );
}

function Row({ label, value }) {
  return (
    <tr className="border-b border-gray-800/50">
      <td className="py-1.5 text-gray-500">{label}</td>
      <td className="py-1.5 text-right font-mono">{value}</td>
    </tr>
  );
}
